composeexample/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^workflows/', include('workflows.urls')),
    url(r'^', include('workflows.urls')),
    #url('', include('social.apps.django_app.urls', namespace='social')),
    #url('', include('social.apps.django_app.urls', namespace='social')),
    #url('', include('django.contrib.auth.urls', namespace='auth')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

workflows/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'workflows'
urlpatterns = [

    url(r'^chat_room1/$', views.chat_room1, name='chat_room1'),
    url(r'^chat_room2/$', views.chat_room2, name='chat_room2'),
    url(r'^chat_room3/$', views.chat_room3, name='chat_room3'),

    url(r'^$', views.index, name='index'),
    url(r'^track/$', views.track, name='track'),
    url(r'^track_modeler/$', views.track_modeler, name='track_modeler'),
    url(r'^create_job/job/$', views.saveXML, name='saveXML'),
    url(r'^create_funding/funding/$', views.saveXML, name='saveXML'),
    url(r'^create_news/announce/$', views.saveXML, name='saveXML'),
    url(r'^create_XML/modeler/$', views.saveXML, name='saveXML'),
    url(r'^create_job/$', views.create_job, name='create_job'),
    url(r'^create_funding/$', views.create_funding, name='create_funding'),
    url(r'^create_news/$', views.create_news, name='create_news'),
    url(r'^create_XML/$', views.create_XML, name='create_XML'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^create/$', views.create, name='create'),
    url(r'^modeler/$', views.modeler, name='modeler'),
    url(r'^create/modeler/$', views.saveXML, name='saveXML'),
    url(r'^(?P<workflow_id>[0-9]+)/modeler/$', views.saveEditedXML, name='saveEditedXML'),
    url(r'^profileedit/$', views.profileEdit, name = 'profileedit'),
    url(r'^register_user/$', views.register_user, name='register_user'),
    url(r'^view_profile/$', views.view_profile, name='view_profile'),
    url(r'^profileDetail/$', views.profileDetail, name='profileDetail'),
    url(r'^job/$', views.job, name='job'),
    url(r'^announce/$', views.announce, name='announce'),
    url(r'^task_noti/$', views.task_noti, name='task_noti'),
    url(r'^funding/$', views.funding, name='funding'),
    url(r'^(?P<workflow_id>[0-9]+)/$', views.editingWorkflow, name='editWorkflow'),
    url(r'^login_user_google/$', views.login_user_google, name='login_user_google'),
    url(r'^design_form/$', views.design_form, name='design_form'),
    url(r'^openXML/$', views.openXML, name='openXML'),
    url(r'^publish/$', views.publish, name='publish'),
    url(r'^tasks/$', views.tasks, name='tasks'),
    url(r'^(?P<task_id>[0-9]+)/do_task/$', views.do_task, name='do_task'),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workflows/forms.py
from django.contrib.auth.models import User
from django import forms

from .models import *


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class StudentForm(forms.ModelForm):
    class Meta:
        model = StudentModel

        fields = ['profileLogo',
                  'userType',
                  'tittle',
                  'firstName',
                  'lastName',
                  'dateOfBirth',
                  'department',
                  'mobile',
                  'email',
                  'loopId',
                  'facebookAddress',
                  ]

    def __init__(self, *args, **kwargs):
        super(StudentForm, self).__init__(*args, **kwargs)
        self.fields['loopId'].required = False
        self.fields['profileLogo'].required = False


class WorkflowTemplateForm(forms.ModelForm):
    class Meta:
        model = WorkflowTemplate

        fields = ['name',
                  'description',

                ]

workflows/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from .models import *
from django.views.decorators.csrf import csrf_exempt
import json
from channels import Group
from .forms import *

from workflows.WorkflowEngine import *
import xml.etree.ElementTree as ET

from django.shortcuts import render
import social.apps.django_app.default.models as sm
from django.contrib.auth import authenticate, login, logout
import json
import ast

def chat_room1(request):
    if not request.user.is_authenticated():
        return render(request, 'workflows/login.html')
    else:
        user = request.user
        return render(request, 'workflows/chat_room1.html', {'user': user.username})

def chat_room2(request):
    if not request.user.is_authenticated():
        return render(request, 'workflows/login.html')
    else:
        user = request.user
        return render(request, 'workflows/chat_room2.html', {'user': user.username})

def chat_room3(request):
    if not request.user.is_authenticated():
        return render(request, 'workflows/login.html')
    else:
        user = request.user
        return render(request, 'workflows/chat_room3.html', {'user': user.username})

def tasks(request):
    if not request.user.is_authenticated():
        return render(request, 'workflows/login.html')
    else:
        user = request.user
        assignedTasks = PendingTask.objects.filter(assignToUser=user)
        return render(request, 'workflows/tasks.html', {'assignedTasks': assignedTasks})

def do_task(request,task_id):
    if request.method == "POST": #Executing tasks

        print(request.POST)
        user = request.user
        task = get_object_or_404(PendingTask,pk=task_id)
        xml = task.belongToWFId.xml

        root = ET.fromstring(xml)

        parser = XMLParser(root)
        parser.createCollaboration()
        parser.createLaneset()
        parser.createProcess()

        nodes = parser.nodes
        lanes = parser.lanes
        flows = parser.flows
        elems = parser.elems

        workflow_engine = WorkflowExecution(flows[task.currentFlow],nodes,flows)
        workflow_engine.run()


        if workflow_engine.task == 1:
            print("HLEFOEOFEF")



            flow_id = workflow_engine.run().id
            target_task = flows[flow_id].target
            assignedUser = nodes[target_task].lane.name
            assignedUsers = assignedUser.split(",")
            task_name = nodes[target_task].name

            form = workflow_engine.form
            pending_task = PendingTask(form=form, listener=User.objects.get(username=assignedUsers[0]),
                                       belongToWFId=task.belongToWFId, taskName=task_name, currentFlow=flow_id, state=1)
            pending_task.save()

            for i in range(0,len(assignedUsers)):

                us = User.objects.get(username=assignedUsers[i])

                pending_task.assignToUser.add(us)


            #newjson = {}

            '''
            for form_elem_key, form_elem_value in request.body.iteritems():
                if form_elem_key != 'csrfmiddlewaretoken' and form_elem_key != 'submit':
                    print("hello")
            '''
            global dict
            print(xml)
            input = dict(request.POST)
            for i in range(len(root)):
                print("OK-1")
                if "process" in root[i].tag:
                    print("OK-2")
                    # noinspection PyPackageRequirements
                    for child in root[i]:
                        print("OK-3")
                        print(child.get('id'))
                        print("TASK ID: "+flows[flow_id].source)
                        if child.get('id') == flows[flow_id].source:
                            print("OK-4")
                            for doc in child:
                                print("OK-5")
                                if "documentation" in doc.tag:
                                    print(doc.text)
                                    form = doc.text
                                    form = form.replace("\n", "").replace("\r", "")
                                    json_form = json.loads(form)
                                    print(json_form)
                                    print(len(json_form))
                                    for j in json_form:
                                        print(j)
                                        if 'name' in j:
                                            for key, value in input.items():
                                                if j["name"] == key:
                                                    j["value"] = value[0]


                                                    doc.text = json.dumps(json_form)


            #print("JSON_FORM",json_form)
            print(root)
            print(ET.tostring(root))

            '''

            dict_json = {}
            dict_json['action'] = "notification"
            taskId = pending_task.taskId
            lst = [task_name, nodes[target_task].lane.name, task.belongToWFId.executingDate.strftime("%B %d, %Y"), taskId]
            dict_json['data'] = lst
            data_noti = json.dumps(dict_json)
            Group("User-" + assignedUser.username).send({"text": data_noti})


            print(data_noti,assignedUser.username)
            '''

            executing_flow = task.belongToWFId
            executing_flow.currentFlow = flow_id
            executing_flow.xml = ET.tostring(root)
            executing_flow.save()


        elif workflow_engine.exclusive == 1:

            option_list = workflow_engine.run()
            '''
            decisions = []
            for option in option_list:
                decisions.append(option.id)
            '''

            option_list = request.session['options_list']
            decision = request.POST['decisions']

            print(decision)
            flow_id = option_list[decision]
            print(flow_id)
            target_task = flows[flow_id].target
            assignedUser = nodes[target_task].lane.name
            assignedUsers = assignedUser.split(",")
            task_name = nodes[target_task].name

            form = workflow_engine.form
            pending_task = PendingTask(form=form, listener=User.objects.get(username=assignedUsers[0]),
                                       belongToWFId=task.belongToWFId, taskName=task_name, currentFlow=flow_id, state=1)
            pending_task.save()

            for i in range(0, len(assignedUsers)):
                us = User.objects.get(username=assignedUsers[i])

                pending_task.assignToUser.add(us)

            executing_flow = task.belongToWFId
            executing_flow.currentFlow = flow_id
            executing_flow.save()

        elif workflow_engine.parallel == 1:
            incom_flow_id_list =  workflow_engine.run()

            #Joining parallel tasks
            if workflow_engine.join == 1:
                count = 0
                for i in range(0,len(incom_flow_id_list)):
                    if PendingTask.objects.filter(currentFlow = nodes[flows[incom_flow_id_list[i]].source].incoming).exists():
                        count+=1
                        print("OKOKOKOKOERGRTGTGJTROGJREPGWEGJREPG")

                if count == 1:


                    next_flow = workflow_engine.joinOutgoing
                    target_task = flows[next_flow].target
                    #assignedUser = User.objects.get(username=nodes[target_task].lane.name)
                    '''
                    task_name = nodes[target_task].name

                    pending_task = PendingTask(assignToUser=assignedUser, form="", listener=assignedUser,
                                               belongToWFId=task.belongToWFId, taskName=task_name, currentFlow=next_flow,
                                               state=1)
                    pending_task.save()

                    '''
                    assignedUser = nodes[target_task].lane.name
                    assignedUsers = assignedUser.split(",")
                    task_name = nodes[target_task].name

                    form = workflow_engine.form
                    pending_task = PendingTask(form=form, listener=User.objects.get(username=assignedUsers[0]),
                                               belongToWFId=task.belongToWFId, taskName=task_name, currentFlow=next_flow,
                                               state=1)
                    pending_task.save()

                    for i in range(0, len(assignedUsers)):
                        us = User.objects.get(username=assignedUsers[i])

                        pending_task.assignToUser.add(us)

                    executing_flow = task.belongToWFId
                    executing_flow.currentFlow = next_flow
                    executing_flow.save()
                else:
                    task.delete()
                    assignedTasks = PendingTask.objects.filter(assignToUser=user)
                    return render(request, 'workflows/tasks.html', {'assignedTasks': assignedTasks})

            #Splitting parallel tasks
            else:
                flow_id_list = workflow_engine.run()
                for i in range(0,len(flow_id_list)):
                    target_task = flows[flow_id_list[i]].target
                    '''
                    assignedUser = User.objects.get(username=nodes[target_task].lane.name)
                    task_name = nodes[target_task].name
                    pending_task = PendingTask(assignToUser=assignedUser, form="", listener=assignedUser,
                                           belongToWFId=task.belongToWFId, taskName=task_name, currentFlow=flow_id_list[i], state=1)
                    pending_task.save()
                    '''

workflows/templates/workflows/base.html
<!-- FlatFy Theme - Andrea Galanti /-->
<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if IE 9]>    <html class="no-js ie9" lang="en"> <![endif]-->
<!--[if gt IE 9]><!-->
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="Flatfy Free Flat and Responsive HTML5 Template ">
    <meta name="author" content="">

    <title>Workflows – An automate workflows engine for everyone!</title>

    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom Google Web Font -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic'
          rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Arvo:400,700' rel='stylesheet' type='text/css'>

    <!-- Custom CSS-->
    <link href="{% static 'css/general.css' %}" rel="stylesheet">

    <!-- Owl-Carousel -->
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'css/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'css/owl.theme.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">

    <!-- Magnific Popup core CSS file -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <script src="{% static 'js/modernizr-2.8.3.min.js' %}"></script>

    <!-- fb chat -->
    <link href= "{%  static 'css/fbstyle.css' %}" rel="stylesheet">
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script src="{%  static 'js/fbscript.js' %}"></script>


    <!-- Modernizr /-->  <!-- Modernizr /-->
    <!--[if IE 9]>
		<script src="js/PIE_IE9.js"></script>
	<![endif]-->
    <!--[if lt IE 9]>
		<script src="js/PIE_IE678.js"></script>
	<![endif]-->

    <!--[if lt IE 9]>
		<script src="js/html5shiv.js"></script>
	<![endif]-->


    <!-- Channel -->
    <script>
		// Note that the path doesn't matter for routing; any WebSocket
		// connection gets bumped over to WebSocket consumers
		socket = new WebSocket("ws://" + window.location.host + "/chat/");
		socket.onopen = function() {
            socket.send(JSON.stringify({type: "Login", user: "", password: ""}))
		}
		// Call onopen directly if socket is already open
		if (socket.readyState == WebSocket.OPEN) socket.onopen();
	</script>


    <style>

        .navbar-default {
            position: fixed;
            top: 0px;
        }

    </style>

</head>

<body id="home">

<!-- Preloader -->
<div id="preloader">
    <div id="status"></div>
</div>

<!-- NavBar-->
<nav class="navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'workflows:register' %}">{% block title %}Workflows
                Engine{% endblock %}</a>
        </div>

        <div class="collapse navbar-collapse navbar-right navbar-ex1-collapse">
            <ul class="nav navbar-nav">

                <li class="menuItem"><a href="{% url 'workflows:tasks' %}">Task</a></li>

                <li class="menuItem"><a href="{% url 'workflows:track' %}"> Track </a>
                    <!--
                      <div class="chat_box">
                        <div class="chat_head"> Chat Box</div>
                        <div class="chat_body">
                        <div class="user"> Krishna Teja</div>
                        </div>
                      </div> -->
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Profile <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'workflows:profileedit' %}">Edit Profile</a></li>
                        <li><a href="{% url 'workflows:profileDetail' %}">View Profile</a></li>

                    </ul>
                </li>

                <li class="menuItem"><a href="{% url 'workflows:task_noti' %}">Community</a></li>
                <li class="menuItem"><a href="{% url 'workflows:logout_user' %}">Logout</a></li>
            </ul>
        </div>

    </div>
</nav>

<!--

<div class="msg_box" style="right:290px">
	<div class="msg_head">Krishna Teja
	<div class="close">x</div>
	</div>
	<div class="msg_wrap">
		<div class="msg_body">
			<div class="msg_a">This is from A	</div>
			<div class="msg_b">This is from B, and its amazingly kool nah... i know it even i liked it :)</div>
			<div class="msg_a">Wow, Thats great to hear from you man </div>
			<div class="msg_push"></div>
		</div>
	<div class="msg_footer"><textarea class="msg_input" rows="4"></textarea></div>
</div>
</div>
-->

<!-- FullScreen -->
{% block body %}
{% endblock %}



<!-- Banner Download -->
<!--

<div id="downloadlink" class="banner">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 text-center wrap_title">
            <h2>Download Free</h2>
            <p class="lead" style="margin-top:0">Pay with a Tweet</p>
            <p><a class="btn btn-embossed btn-primary view" role="button">Free Download</a></p>
         </div>
        </div>
    </div>
</div>
-->

<footer>

    <div class="container">
        <div class="row">

            <!--
          <div class="col-md-7">


            <h3 class="footer-title">Follow Me!</h3>
            <p>Vuoi ricevere news su altri template?<br/>
              Visita Andrea Galanti.it e vedrai tutte le news riguardanti nuovi Theme!<br/>
              Go to: <a  href="http://andreagalanti.it" target="_blank">andreagalanti.it</a>
            </p>


			<a rel="cc:attributionURL" href="http://www.andreagalanti.it/flatfy"
		   property="dc:title">Flatfy Theme </a> by
		   <a rel="dc:creator" href="http://www.andreagalanti.it"
		   property="cc:attributionName">Andrea Galanti</a>
		   is licensed to the public under
		   <BR>the <a rel="license"
		   href="http://creativecommons.org/licenses/by-nc/3.0/it/deed.it">Creative
		   Commons Attribution 3.0 License - NOT COMMERCIAL</a>.


          </div>
            -->

            <div class="col-md-5">
                <div class="footer-banner">
                    <h3 class="footer-title">Development Team</h3>
                    <ul>

                        <li>Jirapa L.</li>
                        <li>Pimpisa W.</li>
                        <li>Chusanart Ph.</li>

                    </ul>

                </div>
            </div>
        </div>
    </div>
</footer>

<!-- JavaScript -->
<script src='https://code.jquery.com/jquery-2.2.4.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js'></script>
<script src='https://formbuilder.online/assets/js/form-builder.min.js'></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/owl.carousel.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script src='http://kevinchappell.github.io/formBuilder/assets/js/form-render.min.js'></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.4.0/highlight.min.js'></script>
<script src=" {% static 'js/form-render.js' %} "></script>

<!-- StikyMenu -->
<script src="{% static 'js/stickUp.min.js' %}"></script>

<script type="text/javascript">
    jQuery(function ($) {
        $(document).ready(function () {
            $('.navbar-default').stickUp();

        });
    });
</script>


<!-- Smoothscroll -->
<script type="text/javascript" src="{% static 'js/jquery.corner.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script>
    new WOW().init();
</script>
<script src="{% static 'js/classie.js' %}"></script>
<script src="{% static 'js/uiMorphingButton_inflow.js' %}"></script>
<!-- Magnific Popup core JS file -->
<script src="{% static 'js/jquery.magnific-popup.js' %}"></script>

<link rel='stylesheet' href='https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css'>
</body>
<!---->
</html>

workflows/templates/workflows/login.html
{% extends 'workflows/base_visitor.html' %}
{% block signup %}{% url 'workflows:register' %}{% endblock %}
{% block body %}

<div id="contact" class="content-section-a">
		<div class="container">
			<div class="row">

			<div class="col-md-6 col-md-offset-3 text-center wrap_title">
				<h2>Sign In</h2>


			<form role="form" action="{% url 'workflows:login_user'%}" method="post" enctype="multipart/form-data">
                {% csrf_token %}

				<div class="col-md-6" style = "left:27%">
					<div class="form-group">
						<label for="InputName">Name</label>
						<div class="input-group">
							<input type="text" class="form-control" name="username" id="InputName" placeholder="Enter Name" required>
							<span class="input-group-addon"><i class="glyphicon glyphicon-ok form-control-feedback"></i></span>
						</div>
                    </div>


					<div class="form-group">
                        <label for="InputPassword">Password</label>
						<div class="input-group">
							<input type="password" class="form-control" id="password" name="password" placeholder="Enter password" required  >
							<span class="input-group-addon"><i class="glyphicon glyphicon-ok form-control-feedback"></i></span>
						</div>
					</div>

                    <div class="panel-footer">
                        Don't have an account? <a href="{% url 'workflows:register' %}"> <br>Click hereeee</a> to register.
                    </div>


                 <div class="panel-footer">
                    Don't have an account? <a href="{% url 'workflows:register' %}"> <font color="red"><br>Click here </font></a> to register.
                </div>




                    <input type="submit" name="submit" id="submit" value="Submit" class="btn wow tada btn-embossed btn-primary pull-right">

				</div>



			</form>


<!--


-->


			</div>
		</div>
	</div>





 <!--
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <form role="form" action="{% url 'workflows:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'workflows:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

 -->


{% endblock %}

workflows/templates/workflows/pendingTask.html
{% extends 'workflows/base.html' %}
{% block title %}Welcome {{ user.username }}! {% endblock %}
{% block body %}
{% load staticfiles %}
<style>
    body { padding-top: 70px; }
</style>
Helloooooo
    Hleorf
<script>
    var checkedList = {{ checkedList|safe }}
    for (var i = 0; i < checkedList.length; i++) {
        console.log(checkedList[i]);
        document.write(checkedList[i]);
}
</script>
{% endblock %}

workflows/templates/workflows/task_noti.html
{% extends 'workflows/base.html' %}
{% block title %}Welcome {{ user.username }}! {% endblock %}
{% block body %}
    {% load staticfiles %}

    <style>
        input[type=text] {
            width: 130px;
            box-sizing: border-box;
            border: 2px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
            background-color: white;
            background-position: 10px 10px;
            background-repeat: no-repeat;
            padding: 12px 20px 12px 40px;
            -webkit-transition: width 0.4s ease-in-out;
            transition: width 0.4s ease-in-out;
            margin-top: 80px;
            margin-left: 50px;
        }

        input[type=text]:focus {
            width: 90%;
        }

        table {
            border: 2px solid dimgray;
            width: 90%;
            margin-left: 50px;
            margin-top: 50px;
            margin-bottom: 50px;
        }
        tr{
            border: 1px solid grey;
        }


    </style>

<div class="row">

        <form>
            <div class = "col text-center">
            <a href="{% url 'workflows:chat_room1' %}" class="btn btn-primary btn-lg active" style="margin-top: 10%; margin-bottom: 5%;  ">Workflow Community</a>
            <a href="{% url 'workflows:chat_room2' %}" class="btn btn-primary btn-lg active" style="margin-top: 10%; margin-bottom: 5%;">Talk with us</a>
            <a href="{% url 'workflows:chat_room3' %}" class="btn btn-primary btn-lg active" style="margin-top: 10%; margin-bottom: 5%;">Build your team</a>
                </div>
        </form>


</div>

     <div class="content-section-b">
                    <div class="container">
                        <div class="row">
                            <h4 class="section-heading">Chatting Service :D {{user.username}}</h4>

            </div>
                        <div class="content">
                            <div id="chat-section"></div>
                            <input type="textarea" id="textarea" class="form-control" placeholder="Type Something..." style="width: 800px">
                            <button id="send-button"  class=" btn-embossed btn-primary pull-right">Send</button>
                        </div>

                            </body>

                        <script>
                            socket = new WebSocket("ws://" + window.location.host + "/chat/");
                            socket.onmessage = function(e) {
                                var chatSection = document.getElementById("chat-section");
                                var p = document.createElement('p');
                                var node = document.createTextNode(e.data);
                                p.appendChild(node);
                                chatSection.appendChild(p);
                            };
                            if (socket.readyState == WebSocket.OPEN)
                                socket.onopen();
                            var sendButton = document.getElementById("send-button");
                            sendButton.onclick = function()
                            {
                                var msg = document.getElementById("textarea").value;
                                var user1 = "{{ user }}";
                                var user1_msg = user1 + ": " + msg;
                                socket.send(JSON.stringify( user1_msg));
                                document.getElementById("textarea").value = '';

                                <!-- put it in database table -->

                            };
                        </script>
                    </div>
                </div>

{% endblock %}

workflows/templates/workflows/track_modeler.html
{% extends 'workflows/base.html' %}
{% block title %}Welcome {{ user.username }}! {% endblock %}
{% block body %}
    {% load staticfiles %}

{% endblock %}